tunnel: aa6f6903-4f08-45dc-a322-194e17c8cd87
credentials-file: /home/nonroot/.cloudflared/aa6f6903-4f08-45dc-a322-194e17c8cd87.json
# 안정성을 위해 QUIC 대신 HTTP/2 사용(네트워크 품질이 낮은 환경 대비)
protocol: http2
# ingress:
#   - hostname: app.gostock.us
#     service: http://npm:80
#     originRequest:
#       noTLSVerify: true
#   - hostname: auth.gostock.us
#     service: http://authelia:9091
#     originRequest:
#       noTLSVerify: true
#   - service: http_status:404
ingress:
  - hostname: app.gostock.us
    service: http://mcp_frontend:3000
  - hostname: api.gostock.us
    service: http://mcp_backend:8000
  - service: http_status:404
loglevel: info

