#!/bin/bash
echo "Cloud Container 과정 의존성 설치 스크립트"
echo "=========================================="

echo "Python 패키지 설치 중..."
pip install -r requirements.txt

echo ""
echo "CLI 도구 설치 확인..."
echo ""
echo "1. Docker 설치:"
echo "   curl -fsSL https://get.docker.com -o get-docker.sh"
echo "   sudo sh get-docker.sh"
echo ""
echo "2. GCP CLI 설치:"
echo "   curl https://sdk.cloud.google.com | bash"
echo "   exec -l $SHELL"
echo ""
echo "3. kubectl 설치:"
echo "   curl -LO https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
echo "   sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl"
echo ""
echo "4. Helm 설치:"
echo "   curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash"
echo ""
echo "설치 완료 후 다음 명령어로 확인하세요:"
echo "docker --version"
echo "gcloud version"
echo "kubectl version --client"
echo "helm version"
